### ISSUE TITLE
Support releases in Pagure

### ISSUE THREAD

**Issue by lbarcziova** [packit/ogr#112]
Figure out how to handle releases in Pagure.

**Comment by marusinm** [comment]
There is missing functionality in Pagure API. I created a new [Issue in Pagure repository](https://pagure.io/pagure/issue/4531) for that. @lbarcziova you can subscribe it to get notified when the status of the issue will change.

**Comment by marusinm** [comment]
I was playing around with git tags for Pagure project. When git tag is created Pagure UI shows it as a new release.

I don't know yet if it'll help us with creating new releases, but I created function `get_releases` for Pagure see #117.

**Comment by lachmanfrantisek** [comment]
We are still blocked by the Pagure API.

**Comment by csomh** [comment]
Not a blocker anymore, Pagure API does have support for releases, even if not for older versions. Making this is an Epic to keep stale bot away.

**Comment by lachmanfrantisek** [comment]
> Making this is an Epic to keep stale bot away.

@csomh you can use `pinned` label instead.

https://github.com/packit-service/ogr/blob/fda65c62ee039786f223433367a8c64d353f4692/.github/stale.yml#L5-L10

**Comment by lachmanfrantisek** [comment]
Reopening since we have in the 1.0 milestone..;)
