### ISSUE TITLE
Missing functionality for getting content of a file.

### ISSUE THREAD

**Issue by marusinm** [packit/ogr#115]
In the case of Github, it is possible to get a repository's file content via [API](https://developer.github.com/v3/repos/contents/#get-contents) or [PyGithub lib](https://pygithub.readthedocs.io/en/latest/github_objects/ContentFile.html). In the case of Pagure, I am not sure if it is possible. 

(I need this for release-bot, I can hack it for now, but would be wonderful to have such feature in ogr.)

**Comment by lachmanfrantisek** [comment]
It's already there..;-)

https://github.com/packit-service/ogr/blob/master/ogr/abstract.py#L672
GitHub: https://github.com/packit-service/ogr/blob/master/ogr/services/github.py#L527
Pagure: https://github.com/packit-service/ogr/blob/master/ogr/services/pagure.py#L703
