### ISSUE TITLE
get_email for GitUser

### ISSUE THREAD

**Issue by marusinm** [packit/ogr#126]
We have `get_username` method in GitUser class. At the moment we are missing method `get_email` for both ~~Github~~ and Pagure services.

-----

- [x] GitHub
- [x] GitLab
- [ ] Pagure

**Comment by yzhang2907** [comment]
@marusinm I added the method, will submit PR now. Thank you!

**Comment by lachmanfrantisek** [comment]
Pagure still misses that.

**Comment by lachmanfrantisek** [comment]
Looks like we are missing only Pagure know which does not provide that value.

See: https://src.fedoraproject.org/api/0/#users-tab

**Comment by lachmanfrantisek** [comment]
Can anyone check that, please?

We have two options:
- Create a bug report (since email can be kind of private information, I am not sure if they will be willing to do that) and implement that
- Raise some meaningful exception for Pagure and close this issue. (Preffered by me..)

**Comment by csomh** [comment]
Would it be possible to return `None` for Pagure? I feel an exception would be a little bit harsh.

**Comment by mfocko** [comment]
will resolve with Friday work
