### ISSUE TITLE
Update and link the contribution guide in README

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#165]
- [x] The contribution guide should be accessible from the README.md. (#265 )
- [ ] We need to be sure that the guide is current and describes the testing approach well.
- [ ] Document `/packit` command.

**Comment by RomaneGreen** [comment]
I'd like to tackle this issue

**Comment by lachmanfrantisek** [comment]
@RomaneGreen Thanks for your interest, that was quick!

It's nice that we have a new contributor to work on our contribution guide..;)

**Comment by lachmanfrantisek** [comment]
Still relevant.
