### ISSUE TITLE
Examples for ogr usage using Jupyter notebook

### ISSUE THREAD

**Issue by rpitonak** [packit/ogr#196]
We have recently added a short usage section into the README.md (#195).

It would be nice to create a new folder in the root of this repository called `examples` and demonstrate various ogr functions.

For me, the best way how to do it is to create a [Jupyter notebook](https://jupyter.org/) as it is supported by GitHub and we can easily combine code snippets, with outputs and comments in Markdown.

*update by @lachmanfrantisek*

TODO:
- [ ] Update the example in the README (something short).
- [ ] Create a folder `examples`.
- [ ] Create some interesting examples / usecases using [jupyter-notebook](https://jupyter.org/) in that folder (github can display the `ipynb` files pretty well).
  - Be sure, that you are not commiting your authentication tokens..;)
- [ ] Link the examples in the README or link the `examples/README.md` where we can have more descriptive text for examples and links for the specific `ipynb` files.

**Comment by lachmanfrantisek** [comment]
We still want it.

**Comment by mfocko** [comment]
There is an open PR regarding this issue - #444 with files jupyter notebooks at https://github.com/mfocko/ogr/tree/jupyter/examples (Readme is not done yet).
If there are any other examples you'd like to see and aren't there, please add them here.
