### ISSUE TITLE
Add info about git workflow to contribution guide (and other suggestions)

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#209]
It would be nice to add the following parts to CONTRIBUTING.md

- What is `git rebase` and how to rebase a pull-request.
    - We want to have a git tree like this: 
![Snímek z 2019-09-19 11-43-15](https://user-images.githubusercontent.com/20214043/65233459-2712aa00-dad3-11e9-8849-6bb5babf75fe.png)
    - not this: 
![Snímek z 2019-09-19 11-43-51](https://user-images.githubusercontent.com/20214043/65233488-309c1200-dad3-11e9-93a9-b2b15e8a0f39.png)

- links to documentation we are using when implementing the code for github, gitlab, pagure
    - https://src.fedoraproject.org/api/0/
    - https://pagure.io/api/0/
    - https://pygithub.readthedocs.io/
    - https://python-gitlab.readthedocs.io/
    - ...
 
- How to write a good git commit messages:
    - https://chris.beams.io/posts/git-commit/

**Comment by lachmanfrantisek** [comment]
I am not sure about `good-first-issue` label.

**Comment by TomasTomecek** [comment]
how about we added the req for rebase into pre-commit?

**Comment by lachmanfrantisek** [comment]
> how about we added the req for rebase into pre-commit?

Sounds very good!

**Comment by TomasTomecek** [comment]
so we just need to update our documentation right now, is that correct?

**Comment by lachmanfrantisek** [comment]
We still want that.

**Comment by lachmanfrantisek** [comment]
Since the https://hacktoberfest.digitalocean.com/ starts soon, we should try to fix this. The rebase is enforced via pre-commit, but those links can be helpful and do not need much work to add it.

**Comment by mfocko** [comment]
I'll have a look in the evening and propose some changes in PR
