### ISSUE TITLE
[question] Allow objects representing nonexisting objects

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#214]
Currently, we can instantiate objects (i.e. GitProject), that does not exist.

We probably need to agree on the common understanding of this approach:

1. allow creating non-existing objects
    - add `exists() -> Bool` method
    - add `create() -> ????` methods
    - we do not need to connect to servers on each instantiation
    - due to laziness it can fail at not-predictable places
2. raise an exception in methods like `get_project`
    - easier implementation
    - we need to connect to the remote service even when it is not needed

**Comment by lachmanfrantisek** [comment]
It's also about documenting these "principles"...

**Comment by rpitonak** [comment]
Add parameter `verify=True` to `get_project` method. We would be still able to create "fake projects".

**Comment by lachmanfrantisek** [comment]
We need to at least clarify the outcome from this.

**Comment by mfocko** [comment]
did we do something about this in the end?

**Comment by lachmanfrantisek** [comment]
I don't think so. Do you think we need to take a look? As I wrote above, at least some agreement and, ideally, docs in the contribution guide would be nice.
