### ISSUE TITLE
Implement GitProject.delete()

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#215]
Add method to project classes to delete a project.

AC:
- [ ] In each implementation, add the `delete` method to project class and implement it.
    - If possible/supported. (Document that if it is not possible and raise an exception with a good message.)
- [ ] Add tests for that.

Links:
- https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html
- https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html
- https://pagure.io/api/0/ (not found the possible API call for that on the first look)

**Comment by UmarJ** [comment]
Hey @lachmanfrantisek, I'd like to work on this issue.

**Comment by lachmanfrantisek** [comment]
> Hey @lachmanfrantisek, I'd like to work on this issue.

@UmarJ Nice! Feel free to ask if you need some help with that. (Also [our contribution guide](https://github.com/packit-service/ogr/blob/master/CONTRIBUTING.md) can be helpful.)

**Comment by UmarJ** [comment]
> > Hey @lachmanfrantisek, I'd like to work on this issue.
> 
> @UmarJ Nice! Feel free to ask if you need some help with that. (Also [our contribution guide](https://github.com/packit-service/ogr/blob/master/CONTRIBUTING.md) can be helpful.)

I'll get right on it!

**Comment by NNRepos** [comment]
@lachmanfrantisek would these make sense?
first test inside tests/integration/test_gitlab.py/GenericCommands:
test_create_and_delete_project_from_service():
create project (with gitlab/service.py/project_create)
delete project (with gitlab/service.py/project_delete)

second test inside tests/integration/test_gitlab.py/GenericCommands:
test_create_and_delete_project_from_project():
create project (with gitlab/service.py/project_create)
delete project (with gitlab/project.py/delete)

**Comment by lachmanfrantisek** [comment]
@NNRepos sorry that I missed your comment.

> test_create_and_delete_project_from_project():

It's a hard question related to the multiple tests -- to prepare@clean inside of the tests or use manual preparation. There are at least three ways:
- Do everything as you proposed.
- Create the project manually to avoid problems during the creation.
- Or use some setup/teardown to differentiate the preparation and the test-run.

> test_create_and_delete_project_from_service():

I am not sure we need this method in the service class.
