### ISSUE TITLE
Improve class structure for Labels type

### ISSUE THREAD

**Issue by svenharris** [packit/ogr#263]
The current implementation of labels has no implementation of GitLabel defined in the abstract classes, which would be consistent with what is done for GitUser, GitProject etc. This is leading to inconsistent typing in the library where we have the following function signatures within the codebase:

abstract.py
`def get_issue_labels(self, issue_id: int) -> List[Any]`

github/project.py
`def get_issue_labels(self, issue_id: int) -> List[GithubLabel]`

gitlab/project.py
`def get_issue_labels(self, issue_id: int) -> List[str]`

Would be good to make this consistent and inherit from a base class of GitLabel.

@lachmanfrantisek

**Comment by lachmanfrantisek** [comment]
We need to look at it.

@mfocko You may probably now if this was fixed by your cllas restracture?

**Comment by mfocko** [comment]
> @mfocko You may probably now if this was fixed by your cllas restracture?

nope, it wasn't
what do we expect? just name and colour properties? or also methods and/or setters?

**Comment by lachmanfrantisek** [comment]
The following properties would be nice:
- name
- colour
- description for GitHub/GitLab

**Comment by mfocko** [comment]
what about getting issues/PRs by label? and setters?

looking at API, Pagure has "labels" just as strings that don't seem to be organized like github/gitlab does

**Comment by lachmanfrantisek** [comment]
> what about getting issues/PRs by label? and setters?

:+1: 



> looking at API, Pagure has "labels" just as strings that don't seem to be organized like github/gitlab does

OK, let's have an abstract label class with the name and Git* label classes with the other two properties.
