### ISSUE TITLE
Support get_files()  in Pagure

### ISSUE THREAD

**Issue by lbarcziova** [packit/ogr#310]
Implement `get_files()` method in Pagure.

- Structure can be seen in the docstring of the code that implements that: https://pagure.io/pagure/blob/dd207ee/f/pagure/api/project.py#_709
- Example: https://pagure.io/api/0/pagure/tree

**Comment by lachmanfrantisek** [comment]
@lbarcziova do you know more about implementation? Are we blocked by the Pagure API?

**Comment by lbarcziova** [comment]
I still cannot find anything related in the Pagure API documentation, so we are blocked.

**Comment by lachmanfrantisek** [comment]
@lbarcziova thanks for the info

**Comment by lachmanfrantisek** [comment]
Some possibility if we really want:
https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols

**Comment by lachmanfrantisek** [comment]
Here is a pagure issue: https://pagure.io/pagure/issue/4808

**Comment by lachmanfrantisek** [comment]
No, stale-bot, Pingu is working on this. :tada:

**Comment by lachmanfrantisek** [comment]
Pingu [implemented](https://pagure.io/pagure/c/dd207ee) that a few days ago.

It should be in the `5.11` version so we can start working on it.
