### ISSUE TITLE
Assigning Issues to based on usernames.

### ISSUE THREAD

**Issue by saisankargochhayat** [packit/ogr#329]
Is it possible to assign Issues to particular user-names using the issue object by any chance?

#### Github
- github-api: https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue
- pygithub: https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html

#### Gitlab
- gitlab-api: https://docs.gitlab.com/ee/api/issues.html#edit-issue
- python-gitlab: https://python-gitlab.readthedocs.io/en/stable/gl_objects/issues.html
- example of the code: https://gitlab.fi.muni.cz/xlachma1/figitool/blob/master/figitool/figitool.py#L576
```python
            user_id = gitlab_instance.users.list(username=login)[0].id
            gitlab_mr.assignee_id = user_id
            gitlab_mr.save()
```

#### Pagure:
- https://src.fedoraproject.org/api/0/#issues
  - -> Create a new issue
  - -> Assign an issue

### TODO:

- [ ] add `assignee` argument to methods for creating the issue
  - in the `abstract.py`
  - for each implementation
  - add tests for it
- [ ] add the get/set property for the Issue classes
  - in the `abstract.py`
  - for each implementation
  - add tests for it

updated by @lachmanfrantisek

**Comment by lachmanfrantisek** [comment]
@saisankargochhayat thanks for the suggestion. Currently, it's not possible, but it should not be hard to implement it.

I've updated your description so anyone can start working on it.

**Comment by nasirhm** [comment]
I would like to work on it.

**Comment by lachmanfrantisek** [comment]
@nasirhm it would be nice!

If you need some help, feel free to ask.

**Comment by nasirhm** [comment]
Thank you @lachmanfrantisek It would take some time for me to be familiar with the infrastructure and work on it.

**Comment by mfocko** [comment]
I'll have a look

**Comment by shreyaspapi** [comment]
@mfocko are you still working on this?

**Comment by mfocko** [comment]
> @mfocko are you still working on this?

You can take it if you want ;)

**Comment by shreyaspapi** [comment]
Can we have multiple assignees in pagure issues?

**Comment by nasirhm** [comment]
@shreyaspapi Nope, We don't.
