### ISSUE TITLE
better is_private method for pagure projects

### ISSUE THREAD

**Issue by dhodovsk** [packit/ogr#330]
AFAIK at the moment it is not possible to get the info about whether the repository is private or not in pagure. Now we depend on the info that in src.fedoraproject.org and pagure.io, the private repositories are not allowed. 

Note: Will this be an issue for https://git.centos.org/?

**Comment by TomasTomecek** [comment]
> Note: Will this be an issue for https://git.centos.org/?

I hope not, all should be public.

**Comment by lachmanfrantisek** [comment]
It would still be nice to not need to hardcode the values for know instances.

**Comment by lachmanfrantisek** [comment]
It looks like we don't know about Pagure instance that uses private repositories. Can we pretent it's a rule and hardcode `False` for Pagure projects?

**Comment by csomh** [comment]
I'm fine with that. We can change this when/if it becomes an issue.

**Comment by mfocko** [comment]
Could be probably resolved by creating new service without auth and in case of 404 return `True` (same is happening with github if you try to look up private repo without auth). Will look into it.

**Comment by mfocko** [comment]
blocked by https://pagure.io/pagure/issue/5038

**Comment by mfocko** [comment]
still blocked

**Comment by mfocko** [comment]
blocked

**Comment by mfocko** [comment]
still blocked

**Comment by mfocko** [comment]
seems to be still blocked

**Comment by mfocko** [comment]
afaik still not fixed on upstream
