### ISSUE TITLE
hostname property in the service classes

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#338]
Multiple times in the code (mostly in the `parsing.py`), we need to parse the hostname of the instance.

```python
service_repo_url = parse_git_repo(repo_url.get_instance_url())
service_repo_url.hostname
```

It would be useful to have a `hostame` property in service classes`.

TODO:
- [ ] add the (read-only) property to the `abstract.py`
- [ ] implement the common behaviour in the `base.py` (see the example above)
  - services with multiple instances possible
- [ ] hardcode the value for static instances (GitHub)
- [ ] use that property in places, where we are getting hostname of the instance
- [ ] create some unit tests for that

**Comment by dinolinjob** [comment]
I would like to work on this issue

**Comment by lachmanfrantisek** [comment]
@dinolinjob 
Nice, if you need some help, feel free to aks. The testing part is a bit tricky for the first time. (See our [contribution guide](https://github.com/packit-service/ogr/blob/master/CONTRIBUTING.md) for some info.)
