### ISSUE TITLE
Document the usage of custom instances and certificates

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#356]
We need to document usage of ogr on custom/internal instances:

- [ ] usage of `instance_url`
- [ ] setup of custom/internal certificates:
  - export `REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt`
  - ignore the SSL verification (`ssl_verify` argument)

**Comment by csomh** [comment]
We still need this, I think.

**Comment by lachmanfrantisek** [comment]
stale-bot, you've closed the non-stale issue once again !

**Comment by csomh** [comment]
still needed

**Comment by lachmanfrantisek** [comment]
This can be now easily documented in the method/class dosctring that will be shown on our doc page: https://packit.github.io/ogr/

**Comment by lachmanfrantisek** [comment]
My previous comment is still valid -- any volunteer for this quick improvement?
