### ISSUE TITLE
introduce a class for a git branch

### ISSUE THREAD

**Issue by TomasTomecek** [packit/ogr#359]
and ideally link it with pull request and git project

The expectation here is that when ogr returns name of a branch, it would return a GitBranch instance instead.

The class should contain at minimum:
* name
* be linked to a repository
* commit SHA of the HEAD

Would be nice if:
* there was a connection to a PR if there is one
* datetime it was created
* datetime of last change

**Comment by lachmanfrantisek** [comment]
> GitBranch

Don't you mean the class from python-git (or how it is called)?

I would go with some custom class because using those classes independently is hard.

**Comment by TomasTomecek** [comment]
> > GitBranch
> 
> Don't you mean the class from python-git (or how it is called)?

I don't.

Since github and others give us a ton of metadata about branches, we could utilize that information in a new class and over time, add more properties and methods to the class.

> I would go with some custom class because using those classes independently is hard.

Absolutely.

**Comment by TomasTomecek** [comment]
Since we haven't implemented this in a year, I am going to close.
