### ISSUE TITLE
edited on Gitlab's commit flag

### ISSUE THREAD

**Issue by mfocko** [packit/ogr#413]
Follow-up of #344 (PR: #374)

API docs (https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit):
> Adds or updates a build status of a commit.

Gitlab API suggests that setting commit flag can update existing one, which could mean this issue is blocked by API.

Updating could also mean:
1.  adding new commit flag that replaces old one
2.  adding new commit flag, but keeping the old one

Example output from docs doesn't contain commit flag with same name.

**Comment by mfocko** [comment]
Looked into it, summary:
1. created a pending commit status
   - `created_at` was set, `started_at` and `finished_at` is `null`
2. set it to running
   - `created_at` persisted, `started_at` was set
3. set it to failed
   - `created_at` and `started_at` was kept, `finished_at` was set
4. set it to success
   - creates new commit status with just `created_at` and `finished_at`; previous one is marked as _retried_

From my understanding there is no way we could implement edited, since any edit (even with posting the same state and context) results in a new commit status.

**Comment by lachmanfrantisek** [comment]
So at least some info, warning, exception?
