### ISSUE TITLE
Implement patch property in GitlabPullRequest and GithubPullRequest

### ISSUE THREAD

**Issue by jpopelka** [packit/ogr#416]
https://github.com/packit-service/ogr/pull/415 implements `PagurePullRequest.patch` property to get a patch from a pull request.
`Gitlab` & `Github` implementation are missing.

Update by @lachmanfrantisek :

The task is to implement `patch` property fo `GithubPullRequest` and `GitlabPullRequest` that will return `patch` of the changes for pull-request (not the URL of it).

- Github:
    - URL of patch: https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.patch_url
    - The URL looks like this: https://patch-diff.githubusercontent.com/raw/packit/packit-service/pull/1003.patch
    - But this one works as well: https://github.com/packit/ogr/issues/416.patch
- Gitlab: https://python-gitlab.readthedocs.io/en/stable/gl_objects/mrs.html
    - I am not sure if `diffs` will work.
    - The same approach as in GitHub (adding `.patch` to the URL) works well: https://gitlab.com/cki-project/kernel-ark/-/merge_requests/800.patch

**Comment by lachmanfrantisek** [comment]
We might want to implement this to be able to have source-gits on GitLab.
