### ISSUE TITLE
Implement request_access for project

### ISSUE THREAD

**Issue by shreyaspapi** [packit/ogr#440]
Add method where user can request access for a project.

- Gitlab - Implemented here - #439 
- Github - After looking into https://pygithub.readthedocs.io/en/latest/index.html (Seems its not possible in Github to request for project access)
- Pagure - Unsure about the support (But unable to find anything here - https://pagure.io/api/0/#projects-tab)

**Comment by lachmanfrantisek** [comment]
@shreyaspapi if they don't support this, what about raising `NotImplementedError` with the specific message (e.g. "Not possible on GitHub") for each forge?

**Comment by shreyaspapi** [comment]
Implemented in #439.
