### ISSUE TITLE
[github] Use check-runs for richer API

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#461]
There is a [check-runs API](https://docs.github.com/en/rest/reference/checks) that allows more functionality and e.g `neutral` state requested in https://github.com/packit/packit-service/issues/760.

Unfortunately, it's [not implemented in PyGithub yet](https://github.com/PyGithub/PyGithub/issues/1621).

This project builds on top of `PyGithub` and implements that: https://github.com/webknjaz/check-in/blob/master/check_in/github_api.py

We can either help on `PyGithub` side or implement it here or wait for `PyGithub`.

**Comment by lachmanfrantisek** [comment]
https://github.com/PyGithub/PyGithub/issues/1621#issuecomment-703189602: ..;(
> stale bot closed this 28 days ago

**Comment by dhruvmanila** [comment]
Hey, I wanted the checks API for my side project and so I completed the CheckRun feature :) https://github.com/PyGithub/PyGithub/pull/1727. Once that is merged and if I get the permission to work on top of this https://github.com/PyGithub/PyGithub/pull/1646, I might complete the CheckSuite feature as well.

**Comment by lachmanfrantisek** [comment]
@dhruvmanila Thanks for your work and for letting us know!

**Comment by mfocko** [comment]
looks like not blocked anymore, might have look into it

**Comment by lachmanfrantisek** [comment]
This is still something we want to work on.

**Comment by lachmanfrantisek** [comment]
@mfocko I hope we are all good here, thanks for implementing this in #592 !
