### ISSUE TITLE
Implement project.exists for GitHub

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#480]
We already have `exists` method implemented for Pagure and the #479 adds the support for GitLab. GitHub is the last one missing.

- [ ] Look at the other implementations and add `exists` method to the `GithubProject` class.

**Comment by path2himanshu** [comment]
Hey @lachmanfrantisek Can you please assign this to me.

**Comment by lachmanfrantisek** [comment]
@path2himanshu sure!

Here is our [contribution guide](https://github.com/packit/ogr/blob/master/CONTRIBUTING.md) and don't forget to ask if you need some help.

**Comment by lachmanfrantisek** [comment]
@path2himanshu Hi, do you still want to work on this?

**Comment by mfocko** [comment]
Closed by #521
