### ISSUE TITLE
Listing of the projects

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#485]
It would be nice to be able to list projects for given criteria:

- namespace
- owner
- search patter
- order options (name, update, activity, ...) (ascending x descending)
- ... feel free to add/propose more (we can implement only a subset for the first version)

Add `list_projects` method:
- [ ] to the `abstract.py` to the `GitService` class
- [ ] for each implementaion `GithubService`, `GitlabService`, `PagureService`
- [ ] implement all (or a subset) of the options from the criteria list above

**Comment by abkosar** [comment]
Hey @lachmanfrantisek, I would like to work on this if that's okay. And just wanted to ask how speedy do you expect this since I'm still kind of new to open source?

Thanks!
Arda

**Comment by lachmanfrantisek** [comment]
@abkosar that would be nice!

This is really nothing urgent. Take your time, get familiar with the code and our [contribution guide](https://github.com/packit/ogr/blob/master/CONTRIBUTING.md)...

And don't forget to ask if you need some help.

**Comment by abkosar** [comment]
@lachmanfrantisek Thanks! I'll start working on it then!

**Comment by abkosar** [comment]
HI @lachmanfrantisek -- So I have been trying to get familiar with the code and I think I kind of understood what I'm supposed to do but just wanted to confirm:
- GithubService/GitlabService/PagureService inherits from BaseGitService and that inherits from GitService.
- I added the following to the GitService:
```
  def list_projects(self, **kwargs: Any) -> GitProject:
        """
        List projects for given criteria

        :param namespace: str
        :param owner: str
        :param search_pattern: str
        """
        raise NotImplementedError
```
- And now I will implement the filtering option for each of the services.

Let me know if that sounds about right!

Thanks!

**Comment by lachmanfrantisek** [comment]
>     * GithubService/GitlabService/PagureService inherits from BaseGitService and that inherits from GitService.

Yes, there is an abstract `GitService` that defines our API, the base class contains shared and helper code between all the implementations. And then there are our implementaions. Same is for other classes.

> I added the following to the GitService:

I would only use full header and `List[GitProject]` as a type annotation:

```python
  def list_projects(self,
      namespace: str = None, owner: str = None, search_patter: str = None
  ) -> List[GitProject]:
        """
        List projects for given criteria

        :param namespace: str
        :param owner: str
        :param search_pattern: str
        """
        raise NotImplementedError
```

> And now I will implement the filtering option for each of the services.
> Let me know if that sounds about right!

:+1:  Yes, it looks right to me.

**Comment by abkosar** [comment]
Sounds good, will do👍

**Comment by abkosar** [comment]
@lachmanfrantisek So more deep dive to the code, I have a point that I want to clarify:

- In `ogr.services.github.user.py`, in GithubUser class there is a `get_projects` function which lists all the projects for the authenticated user. What will be the difference of the `list_projects` function?

**Comment by lachmanfrantisek** [comment]
Good point!

The one in the user class should list only projects of the user, the one we want to implement is to list all the repositories that matches the rules.

**Comment by abkosar** [comment]
Got it, I'm glad I asked it then. So this function will (in a sense) be like the search bar on Github? Regardless of the user it will filter and list all the repos based on the function inputs?

**Comment by lachmanfrantisek** [comment]
@abkosar Yes, exactly.

**Comment by abkosar** [comment]
@lachmanfrantisek  So I spent tonight reading Github Search API's documentation and added `language` to the `list_projects` function as an argument which I thought could be useful:
```
    def list_projects(
        self,
        namespace: str = None,
        owner: str = None,
        search_patter: str = None,
        language: str = None,
    ) -> List["GitProject"]:
        g = self.github
        search_query = f"user:{owner}+language:{language}"
        projects = g.search_repositories(search_query, order="asc")

        return [
            GithubProject(
                repo=repo.name,
                namespace=repo.owner.login,
                github_repo=repo,
                service=self,
            )
            for repo in projects
        ]
```

I couldn't find anything about namespace though, what do you mean by `namespace`? And also by `search_pattern`?

There are multiple ways to search repos like keywords contained in README file, number of starts, forks etc. I just want to move to the right direction.

**Comment by lachmanfrantisek** [comment]
> ... and added language to the list_projects function as an argument which I thought could be useful

:+1: I like that!

> I couldn't find anything about namespace though, what do you mean by namespace? 

username or group, e.g. [packit](https://github.com/packit), [lachmanfrantisek](https://github.com/lachmanfrantisek), or [packit-service/src](https://gitlab.com/packit-service/src).

> And also by search_pattern?

A regular expression that matches the project name.

> There are multiple ways to search repos like keywords contained in README file, number of starts, forks etc. I just want to move to the right direction.

Yes, but let's start with something and enhance later. What do you think? (We also want to support options that we are able to implement across multiple git forges, that are not GitHub-specific.)

**Comment by abkosar** [comment]
> username or group, e.g. packit, lachmanfrantisek, or packit-service/src.

So searching for a group/org or username requires different queries. Then I guess I should either add an `is_org` parameter or maybe an `org_name` parameter in order to differentiate between a user and org search?

> A regular expression that matches the project name.

That sounds doable. So if there is a search pattern it will filter that from the listed projects/repositories?

> Yes, but let's start with something and enhance later. What do you think? (We also want to support options that we are able to implement across multiple git forges, that are not GitHub-specific.) 

I agree. I think let's keep it simple and aim to implement across multiple git forges. After that we can build on top of the existing structure which should be easier.

**Comment by lachmanfrantisek** [comment]
> So searching for a group/org or username requires different queries. Then I guess I should either add an is_org parameter or maybe an org_name parameter in order to differentiate between a user and org search?

What about having `username` argument and `namespace` that will work in a following way:
- use `username` search for `username`
- use both `username` and `group` search for `namespace` since it actually is a namespace (at least on GitHub)

> That sounds doable. So if there is a search pattern it will filter that from the listed projects/repositories?

:+1:

**Comment by abkosar** [comment]
@lachmanfrantisek  Sorry for the late reply man, I am on the verge of an international move so some days are very busy.

> What about having username argument and namespace that will work in a following way:

I will check this option out it seems doable I think. For now I am using PyGithub but let me see what endpoints you have it to do that.

**Comment by lachmanfrantisek** [comment]
@abkosar No problem, take your time..;)

**Comment by abkosar** [comment]
Thanks, appreciate it! 

I think I am done with GithubService. Would you prefer that I do each of them and do a PR or should we check GithubService, optimize it and do the other ones with the optimized logic?

**Comment by lachmanfrantisek** [comment]
We can go by smaller steps and if possible, I would like to have less functionality for all the forges first. And then improve.

**Comment by abkosar** [comment]
Sounds good then. Let me implement the other ones as well and then do a PR so you can review.

**Comment by abkosar** [comment]
Hey @lachmanfrantisek, Merry Christmas! I just settled in (completely) and going to work actively on this from now on, just wanted to give an update.

**Comment by abkosar** [comment]
So I have one question.

Is there an easier way to test what I add? Currently I save my code, from the terminal type `python` and kind of import the `GitlabService` for example and then try to use the `list_projects` function.

It works but it kind of feels cumbersome so just curious if there is an easier way to do it.

**Comment by lachmanfrantisek** [comment]
> Hey @lachmanfrantisek, Merry Christmas! I just settled in (completely) and going to work actively on this from now on, just wanted to give an update.

Thanks for the update.

> Is there an easier way to test what I add? Currently I save my code, from the terminal type python and kind of import the GitlabService for example and then try to use the list_projects function.
> It works but it kind of feels cumbersome so just curious if there is an easier way to do it.

Same as for other git-forges. I would put that into the test cases. (Set of queries with expected results.) We use requre for our tests -- it asks the Gitlab only for the first time and records the responses. The other runs (i.e. in the CI) are offline and with the stable response. It's a bit tricky for the first time but really handy. There is something about that [in our contribution guide](https://github.com/packit/ogr/blob/master/CONTRIBUTING.md#testing). Let us know if you need some help with that.

Thanks. You can open the pull-request and we can discuss various details there...

**Comment by abkosar** [comment]
So I have never used/seen pagure before therefore I decided to do a PR with what I have and then we can discuss here. However when I do my pre-commit checks I get the following errors which I do not know how to fix:

```
ogr/services/pagure/service.py:290: error: Return type "List[PagureProject]" of "list_projects" incompatible with return type "List[GitProject]" in supertype "GitService"
ogr/services/gitlab/service.py:127: error: Return type "List[GitlabProject]" of "list_projects" incompatible with return type "List[GitProject]" in supertype "GitService"
ogr/services/github/service.py:183: error: Return type "List[GithubProject]" of "list_projects" incompatible with return type "List[GitProject]" in supertype "GitService"
```

In abstract.py `list_projects` is defined like this:
```
def list_projects(
        self,
        namespace: str = None,
        user: str = None,
        search_patter: str = None,
        language: str = None,
    ) -> List["GitProject"]:
```

And in each service instead of `List["GitProject"]` I did for example; `List["GithubProject"]`. I also tried keeping them all `List["GitProject"]` however that didn't work either.

Is there a way to fix this?

**Comment by lachmanfrantisek** [comment]
@abkosar It's sometimes tricky to make mypy happy. I would try to go with a general type in all the methods. We already use this approach elsewhere, e.g. here:

https://github.com/packit/ogr/blob/320ba0abd0e76312e9c19db275bc74cb04124560/ogr/services/github/project.py#L270-L278

https://github.com/packit/ogr/blob/320ba0abd0e76312e9c19db275bc74cb04124560/ogr/abstract.py#L978-L984

I hope the warning for that case can be solved.

**Comment by abkosar** [comment]
@lachmanfrantisek So I tried your suggestion:

- `abstract.py`
```
    def list_projects(
        self,
        namespace: str = None,
        user: str = None,
        search_patter: str = None,
        language: str = None,
    ) -> List["GitProject"]:
```

- `github/service.py`
```
    def list_projects(
        self,
        namespace: str = None,
        user: str = None,
        search_patter: str = None,
        language: str = None,
    ) -> List[GitProject]:
```
and for `github` it returns a list of `GithubProjects` which inherits from `BaseGitProject` and that inherits from `GitProject`. But I still get the following errors for both `github` and `gitlab` (since I haven't implemented pagure yet, it just has `raise NotImplementedError`):

```
ogr/services/gitlab/service.py:153: error: Incompatible return value type (got "List[GitlabProject]", expected "List[GitProject]")
ogr/services/gitlab/service.py:153: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
ogr/services/gitlab/service.py:153: note: Consider using "Sequence" instead, which is covariant
ogr/services/gitlab/service.py:153: note: Perhaps you need a type annotation for "gitlab_projects"? Suggestion: "List[GitProject]"
ogr/services/github/service.py:218: error: Incompatible return value type (got "List[GithubProject]", expected "List[GitProject]")
ogr/services/github/service.py:218: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
ogr/services/github/service.py:218: note: Consider using "Sequence" instead, which is covariant
ogr/services/github/service.py:218: note: Perhaps you need a type annotation for "projects"? Suggestion: "List[GitProject]"
Found 2 errors in 2 files (checked 3 source files)
```

**Comment by lachmanfrantisek** [comment]
@abkosar Hi, please create a PR so we can discuss on the code. (You can skip the hooks by adding `-n` to the git command.)

It looks to me like the variable with the list is `List[GitlabProject]` that is (for mypy) not a subtype of `List[GitProject]`. You need to instantiate that variable with setting that type or explicitly state that before return:

```python
result_list : List[GitProject] = []
result_list.append(GitlabProject(...))
return result_list
```
or this:

```python
result_list = []
result_list.append(GitlabProject(...))
result_list : List[GitProject]
return result_list
```

**Comment by lachmanfrantisek** [comment]
Still something we want to have and there is already an open PR solving this.
