### ISSUE TITLE
GithubObject has no attribute "NotSet"

### ISSUE THREAD

**Issue by shreyaspapi** [packit/ogr#490]
By running `pre-commit run --all-files` getting the below error without using the strict mode. I am not sure what NotSet does in this case.
```
ogr/services/github/service.py:169: error: Module has no attribute "NotSet"
```
The changes were made in this PR - https://github.com/packit/ogr/pull/476

**Comment by lachmanfrantisek** [comment]
It's interesting that pygithub uses that as well and zuul didn't complain when it was merged. @mfocko was facing this last week, didn't you?

Isn't this about cached (=old) packages managed by pre-commit?

**Comment by mfocko** [comment]
It's a pretty weird error...
- it's used in PyGithub for some time already, so cache is out of question
- I've been trying to fix it in separate source (completely out of ogr), failed
- glanced through the sources, it seems they don't have the `NotSet` in `GithubObject.pyi`, so the mypy is not aware of its existence...

**Comment by mfocko** [comment]
there was one fedora release EOL already, is this issue still relevant? or can we even safely remove the workaround for different versions?
