### ISSUE TITLE
ogr can't parse a subnamespace in gitlab's URL

### ISSUE THREAD

**Issue by TomasTomecek** [packit/ogr#496]
```
In [1]: from ogr.parsing import parse_git_repo 

In [2]: parse_git_repo("git@gitlab.com:packit-service/src/libvirt.git")                        

In [3]: :( 
   ...:  
```

**Comment by TomasTomecek** [comment]
and this is breaking packit, since it wants to find out the namespace desperately, and can't

**Comment by mfocko** [comment]
right, it's the `:` since, it's used for username, but also could mean port, and for SSH it also separates hostname...

**Comment by lachmanfrantisek** [comment]
Is this some deprecation after the refactor? Or something ssh url specific? (I've fixed that some time ago already...)

**Comment by mfocko** [comment]
ssh url, but it looks like the port is not allowed... so...

```
/tmp % git clone git@git.mfocko.xyz:2222:mfocko/dotfiles.git  
Cloning into 'dotfiles'...
Gitea: Internal Server Error
Unable to get repository owner: 2222:mfocko/dotfiles user does not exist [uid: 0, name: 2222:mfocko, keyid: 0]
```

**Comment by mfocko** [comment]
Sweet, Pagure uses `fork` for HTTP URL and `forks` for SSH URL...

**Comment by TomasTomecek** [comment]
lol `Gitea: Internal Server Error` making devops' job fun

yeah, Hunor also pointed out inconsistency in fork vs. forks

**Comment by mfocko** [comment]
> lol `Gitea: Internal Server Error` making devops' job fun

took port as part of namespace, not a problem on the forge' side :D

I'll probably push some tests first, so we can agree on expected attributes

**Comment by TomasTomecek** [comment]
just verified this is now fixed
