### ISSUE TITLE
`project.get_branches()` should also return the HEAD commits for each branch

### ISSUE THREAD

**Issue by csomh** [packit/ogr#509]
Similar to how `get_tags()` return `GitTag` objects which also store the commit sha, would be nice if `get_branches()` would return `GitBranch` objects with a `head` attribute storing the commit sha of the HEAD of the branch.

Most probably related to #359.

**Comment by lachmanfrantisek** [comment]
Good point!

I've put that point to the issue, you've linked. Is that OK? Can we close this one now?

**Comment by csomh** [comment]
I will leave it up to you. Personally I have the feeling that this and #359 are related but have different time horizons, b/c changing `get_branches()` will require several releases in order to keep the API backwards compatible.

**Comment by lachmanfrantisek** [comment]
Good point, but I would merge it because we need to think about the deprecations in the other card as well.
