### ISSUE TITLE
Add a documentation for API

### ISSUE THREAD

**Issue by Aniket-Pradhan** [packit/ogr#53]
There is no documentation on how to use the library, currently. A documentation will help people on how to use ogr, and showcase it's features and functions.

This can be done by adding the wiki pages (on Github), since the documentation might be quite long and the Wiki will help in segregating several topics (for instance, how to use ogr for GitHub, GitLab and Pagure).

**Comment by rpitonak** [comment]
@Aniket-Pradhan yes I agree with you that we need documentation. We already did some research about possible options here https://github.com/user-cont/kwaciaren/wiki/Documentation and we can start writing once we agree on it.

**Comment by lachmanfrantisek** [comment]
Yes, we still need it.

**Comment by mfocko** [comment]
Fixed by #531 
present at https://packit.github.io/ogr
