### ISSUE TITLE
Add a link to documentation to README

### ISSUE THREAD

**Issue by mfocko** [packit/ogr#534]
Residing at https://packit.github.io/ogr

Follow-up of #531

**Comment by TomasTomecek** [comment]
This is now fixed, right? :)

**Comment by TomasTomecek** [comment]
Oh my, so glad we now have docs here! I won't need to check API in the code any more.

**Comment by mfocko** [comment]
yup, i'm also converting to google format of docstrings, there's no PR, cause it's a lot and no reason to trigger CI :man_shrugging:
