### ISSUE TITLE
Transition to pdoc from pdoc3

### ISSUE THREAD

**Issue by mfocko** [packit/ogr#535]
Currently we use [pdoc3](https://pypi.org/project/pdoc3/) to generate our documentation, it would be in our interest to switch to original project [pdoc](https://pypi.org/project/pdoc/), since it provides built-in search feature and cleaner UI.

Currently can't be used since there is a failure while parsing our source files.

Follow-up of #531

**Comment by abkosar** [comment]
I would like to work on this if that's ok. I don't have any experience with pdoc but I think I can figure it out.

**Comment by lachmanfrantisek** [comment]
@abkosar that would be nice!

@mfocko Does it conflict with your ongoing afford with the doc-string cleanup?

**Comment by mfocko** [comment]
> @mfocko Does it conflict with your ongoing afford with the doc-string cleanup?

I'm not actually sure. I think the problem was with formatting of our code and the parser of `pdoc`, I'll try to have a look if they have some issue open (or already closed) regarding that. If it is «just» formatting and indentation, it might be more complicated to fix on our side.

**Comment by mfocko** [comment]
Cannot reproduce with latest version, so I guess the steps are:

- improve the importing (e.g. `__init__.py`, etc.), since `pdoc` does only what sees, right now if you generate for `ogr` it will show only services and everything nested is ignored
- transition the GitHub Action

**Comment by abkosar** [comment]
Ok cool, so should I move forward with it or should I just hold for now?

**Comment by mfocko** [comment]
I think you can, assigning to you, in case you run into any issues, let us know, we'll figure something out :)

**Comment by abkosar** [comment]
I am still working on it.

**Comment by mfocko** [comment]
@abkosar  I'm sorry, I haven't noticed the comment till today...

In case there is something you need help with, don't hesitate to open PR with whatever you have done and ping us :)

**Comment by abkosar** [comment]
Hi @mfocko -- No worries, I just wrote that comment because the bot marked it as stale so I didn't want the issue to close:)

**Comment by abkosar** [comment]
So I'm focusing on this starting from today. I'll let you guys know if I have any questions!

**Comment by abkosar** [comment]
So, I have one question.

When you say:
> if you generate for ogr it will show only services and everything nested is ignored

Do you mean that pdoc doesn't include them in the documentation? Because when I click `abstract.py` and then `OgrAbstractClass` all the classes which inherit from the `OgrAbstractClass` show up there. 

Do you want all the classes to be listed on the main page of the micro-site that pdoc generates? I want to understand which parts of the current documentation you guys want to be changed.

**Comment by mfocko** [comment]
I see the misunderstanding now. The current implementation is using [pdoc3](https://pypi.org/project/pdoc3/) and we want to transition to [pdoc](https://pypi.org/project/pdoc/). If you generate the docs with `pdoc`, you only get the services that are exported via `__all__`

**Comment by mfocko** [comment]
you can reproduce locally via:

```sh
$ pip3 install --user pdoc
$ pip3 install --user . # from the git repo of ogr
$ pdoc ogr # should also open the browser with the generated docs
```

**Comment by abkosar** [comment]
@mfocko that one-liner is a great help. Apparently, my stage wasn't close to the output of that one-liner.

Now I'm trying to organize the `__init__` files so that it'll give the output you want. I guess that what you guys want right?
