### ISSUE TITLE
mypy cannot use the type annotation

### ISSUE THREAD

**Issue by Roming22** [packit/ogr#559]
The package is not PEP-561 compliant (see https://mypy.readthedocs.io/en/latest/installed_packages.html#creating-pep-561-compatible-packages).

The file `py.typed` need to be added at the root of the ogr package.

**Comment by lachmanfrantisek** [comment]
Good to know, thanks for creating the issue and sending us the PR.

**Comment by mfocko** [comment]
closed by 33f4be5, right?

**Comment by jpopelka** [comment]
yes, #560
