### ISSUE TITLE
[GitHub] Support using the `merge` ref instead of the `head` ref

### ISSUE THREAD

**Issue by mrc0mmand** [packit/ogr#584]
Hello!

During our experience with Packit in systemd we've encountered multiple occurrences of a a scenario where a change in a pull request breaks the Packit CI when combined with a commit pushed into the main branch _after_ the PR was created - in other words: had the PR been rebased before running the CI the issue would have been detected.

For this reason, our other CIs use the _test/merge_ ref GitHub provides for each PR (`refs/pull/XXX/merge` instead of `refs/pull/XXX/head`) which provides a transient merge commit combining the current base branch with the PR changes .

In the GH API the SHA of the merge commit is provided via the `merge_commit_sha` field:
>The value of the `merge_commit_sha `attribute changes depending on the state of the pull request. Before merging a pull request, the `merge_commit_sha` attribute holds the SHA of the test merge commit. After merging a pull request, the `merge_commit_sha `attribute changes depending on how you merged the pull request

(taken from https://docs.github.com/en/rest/reference/pulls#get-a-pull-request).

The PyGithub counterpart is `github.PullRequest.merge_commit_sha` (https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.merge_commit_sha)

GitLab seems to support the `merge_commit_sha` field as well (https://docs.gitlab.com/ee/api/merge_requests.html), but I have a very limited experience with GitLab, so I'm not sure about the details.

Would it be possible to implement this in a similar manner as the `GithubPullRequest.head_commit` property (since it's "just" `github.PullRequest.merge_commit_sha` instead of `github.PullRequest.head.sha)`, and then make it _somehow_ configurable via Packit?

Thank you!

**Comment by mfocko** [comment]
Hi!

So if I understand correctly, you propose two following changes:

1. `merge_commit_sha` to be added to `ogr` API for pull/merge requests, and
2. ability to configure running Packit-as-a-Service on the "merge commit"
   - I recall some discussion regarding this previously
   - I can see one _smallish_ issue in case of merge conflicts, but I guess that could be definitely resolved by falling back to the head of the PR/MR
   - this seems to be related too: https://github.com/packit/packit-service/issues/245

It seems to be more relevant for the service, so if you don't have any objections for those 2 points, I will move transfer the issue there. :)

(Or in the light of https://github.com/packit/packit-service/issues/245, maybe just keep this for the ogr part)

**Comment by mrc0mmand** [comment]
> So if I understand correctly, you propose two following changes:

Exactly!

> * I can see one _smallish_ issue in case of merge conflicts, but I guess that could be definitely resolved by falling back to the head of the PR/MR

In this case it might help checking the `mergeable` field (`github.PullRequest.mergeable` in PyGithub):
>The value of the `mergeable` attribute can be `true`, `false`, or `null`. If the value is `null`, then GitHub has started a background job to compute the mergeability. After giving the job time to complete, resubmit the request. When the job finishes, you will see a non-null value for the `mergeable` attribute in the response. If `mergeable` is `true`, then `merge_commit_sha` will be the SHA of the test merge commit.

But I suspect it might not be the universal solution for all git forges.

>  * this seems to be related too: [packit/packit-service#245](https://github.com/packit/packit-service/issues/245)

Hah, I completely missed this one when I was trying to find if this was already requested, thanks! 
> 
> It seems to be more relevant for the service, so if you don't have any objections for those 2 points, I will move transfer the issue there. :)
> 
> (Or in the light of [packit/packit-service#245](https://github.com/packit/packit-service/issues/245), maybe just keep this for the ogr part)

Feel free to keep/transfer/closed this one then, I've subscribed to packit/packit-service#245 since it's basically what I was trying to request.

Thanks!

**Comment by TomasTomecek** [comment]
Let's keep this one to track the ask for ogr and then continue the discussion for the whole change in the packit-service's issues :)

I think this is a good suggestion, I'm wondering what happens when the PR cannot be merged to the target branch - this is the reason why I think we should support both workflows: building from contributor's branch and building from a merged result. I'd say both are valid workflows.

**Comment by mfocko** [comment]
> I think this is a good suggestion, I'm wondering what happens when the PR cannot be merged to the target branch - this is the reason why I think we should support both workflows: building from contributor's branch and building from a merged result. I'd say both are valid workflows.

At least for GitHub you get `true, false, null`, `true` means "merged", `false` should be conflict, `null` not finished.
In case of GitLab I just checked on of the opened MRs, it seems they don't do it... The merge commit SHA is populated with the actual merge commit after the MR is merged.

**Comment by TomasTomecek** [comment]
>     * If it is only supported by GitHub, it would probably make sense to do the merge locally on our side (positive is no need to keep GitHub jobs in queue till the "merge" is finished, negative is additional cost on our side)

This should be a fairly cheap operation, right? Unless we are merging 5y old PR.

The main problem I can see from my side is if the merge fails with some obscure error message - though we can check how others are doing this, especially zuul and get inspired.

**Comment by martinpitt** [comment]
@TomasTomecek , @mvollmer: FYI, this is the issue we talked about yesterday. We ran into that in https://github.com/cockpit-project/cockpit/pull/15823 as well -- the [packit test failure](http://artifacts.dev.testing-farm.io/c712faf8-5fa4-48cd-a740-b724d81af5fd/) happens because it takes outdated tests: that PR was posted from a slightly out of date  fork, while origin/master got some string changes ("Never lock account" → "Never expire account"). Our code and tests got adjusted, and our `create-archive:` command correctly runs from the merge -- but packit runs the test directly from the proposed branch, *not* the merge commit. So the tests are out of date.

IMHO the default should be to test the merge commit, as that's what will *actually* happen if you merge the PR. At least it should be possible to configure.

> I'm wondering what happens when the PR cannot be merged to the target branch

Then the test should fail early. The PR has conflicts and needs  to be rebased anyway. It is not acceptable to test something outdated with conflicts and then manually merge it with conflict resolution *without* testing the merged result. At least CI systems should not encourage it.

**Comment by martinpitt** [comment]
> we can check how others are doing this, especially zuul and get inspired.

There should be nothing magic to it -- see e.g. [cockpit CI](https://github.com/cockpit-project/bots/blob/master/make-checkout#L45) (`--rebase` is given for all PRs). GitHub workflow's [standard actions/checkout](https://github.com/actions/checkout) also grabs the PR "merge commit" by default, not the fork's  HEAD (you can opt into using the latter).

**Comment by martinpitt** [comment]
... in other words, packit's code doesn't need to do anything explicitly. It should just clone the merge branch as the description says, that one is already rebased.

**Comment by TomasTomecek** [comment]
> ... in other words, packit's code doesn't need to do anything explicitly. It should just clone the merge branch as the description says, that one is already rebased.

I didn't realize it's this simple. It also sounds like it's "the right thing" to do and would also solve some weird behaviour (e.g. a PR is not rebased and contains very outdated packit.yaml or other configs).

Bumping the prio here: @lachmanfrantisek shall we plan this one for the next sprint? Sounds like a trivial thing to implement.

**Comment by allisonkarlitskaya** [comment]
Yay!  Thanks for landing this!  :heart:

**Comment by TomasTomecek** [comment]
@allisonkarlitskaya just to be clear, we still need to actually use this functionality in packit, this is only the first part where we implemented the plumbing :) please watch packit/packit-service#245
