### ISSUE TITLE
Implement fetching GitHub secrets in ogr

### ISSUE THREAD

**Issue by bcrocker15** [packit/ogr#607]
This is PACKIT-1506; GitLab also has a concept of secrets, but I think that
can be addressed as a separate issue.

Edit: needed for https://github.com/packit/packit-service/issues/1122

**Comment by TomasTomecek** [comment]
Agreed, let's focus on GitHub for now.

I'd also love to clarify that fetching of the secrets needs to work when authenticating as a GitHub app.

**Comment by TomasTomecek** [comment]
I'd like to clarify this is about reading GitHub Actions Secrets: https://docs.github.com/en/rest/reference/actions#secrets and *not* the app/oauth secret token.

**Comment by TomasTomecek** [comment]
We just realized that the REST API returns **encrypted** secrets and only GitHub has the private key: we wouldn't be able to decrypt them which means this issue cannot be resolved and we're blocked :/

**Comment by bcrocker15** [comment]
Hope you don't mind, but I captured your IRC dialogue:

<Ben> So, flachman, mfocko... Any ideas?  Can probably write code modeled on code in site-packages/github....

<packit-irc> <mfocko> /glanced through the API, they have PUT & DELETE for
the secrets ._. what happened to GET? :( we could also contribute to the PyGithub

<Ben> Latest version of code in https://github.com/PyGithub/PyGithub.git does,
in fact, have create_secret, which PUTs a secret, and get_public_key, which GETs actions/secrets/public-key

<packit-irc> <mfocko> /There's also ‹delete_secret›; ‹get_public_key› should
return the key for encrypting the secrets when using ‹create› or ‹delete›,
I bet PyGithub uses it  internally, so user doesn't have to; there are a few open
issues (on PyGithub) containing ‹secret›, but related to workflows/GitHub Actions;
looking at the code it might be the easiest and most beneficial to contribute to them, since it's the same thi
...
<packit-irc> end up with code duplication (if it eventually got into the library)

<ttomecek> yeah, that makes sense to contribute the code to pygithub - the
problem is that it will take months till we have it via Fedora stable;
eventually we could have it as a downstream patch or build it in our own
copr repo till it lands in stable
agreed that putting the code into pygithub is the best long-term solution

"You must authenticate using an access token with the admin:org scope
to use this endpoint. GitHub Apps must have the secrets organization
permission to use this endpoint." from the docs, I wonder if we ever
can get that admin:org scope

<packit-irc> <mfocko> /We can't read the original values though... I
think I get why there's no GET in the PyGithub, cause it's GitHub that
provides secrets to GitHub Actions, so they have the private key to
decrypt them... At least the API suggests that GET returns back
«encrypted» secret

<ttomecek> @mfocko indeed so
so the API is completely useless: what's the point of accessing those encrypted secrets? :D

<packit-irc> <mfocko> /You could potentially run both App and Action,
while Action runs on GitHub and App provides secrets to your internal
infra? 🤔 that way you could use get to verify that everything is set
correctly?

<ttomecek> @mfocko but still wouldn't be able to decrypt the secret internally

<packit-irc> <mfocko> /If the action runs some long action ( pun
intended ;) ), you could easily transfer the quota and hosting issues
to the owner of the repository, since you are the one that gets
quotas, not the Action or App itself ( apart from rate-limiting on
APIs, right? :D ); iirc the way the quotas are set per repo

<packit-irc> <mfocko> /Nope, but action runs from workflow where
github provides decrypted value :shrugs:

<ttomecek> GET /secrets/foo would still return
mf2#F2m3f2#$@3mfwefwefwefmo3f instead of "bar" because GitHub has the
private key, as you pointed out above

<packit-irc> <mfocko> /We're talking about different use cases; you
are getting secret from API (e.g. from App); I'm talking directly
about GitHub Action were you would get from GitHub decrypted secret :D

<ttomecek> @mfocko yes, for actions/workflows it's designed well and it's secure
for the API, secrets are useless and write-only :D
it's too late, I'm going to bed, let's talk tomorrow; good night!

<packit-irc> <mfocko> /Or we could run packit in GitHub Action :D good night :)

</end of IRC capture>

Interestingly, I was playing with the examples on 

https://pygithub.readthedocs.io/en/latest/examples/

and discovered that 

    repo.get_public_key()

fails with 

github.GithubException.GithubException: 403 {"message": "Must have admin rights to Repository.", "documentation_url": "https://docs.github.com/rest/reference/actions#get-a-repository-public-key"}

**Comment by bcrocker15** [comment]
We may actually be closer with GitHub; check out this page:

https://docs.gitlab.com/ee/ci/secrets/

Here is a script to install HashiCorp's Vault, mentioned on the gitlab
page; KV-V2, also mentioned on the gitlab page, is part of Vault.

Make sure to 'sudo' this script:

#!/bin/bash
dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
dnf -y install vault

**Comment by lachmanfrantisek** [comment]
@bcrocker15 The workflow you've linked is for GitLab runners -- similarly to Github, this is not how we run the service. We want to support the following workflow:

* User can configure a group of secrets (key-value pairs) somewhere in the UI of the git forge.
    * We don't store the secrets and leave the security/permission problems to the forge developers.
* We want to get those secrets over the API.
    * In Github, we authenticate as a Github application.
    * In GitLab, we authenticate as a service user (=a regular user created for the purpose of the service).

**Comment by lachmanfrantisek** [comment]
> Here is a script to install HashiCorp's Vault, mentioned on the gitlab
> page; KV-V2, also mentioned on the gitlab page, is part of Vault.

I think HashiCorp's Vault itself is just another system for storing secrets -- it fits to our alternative option to support some 3rd party secret provider.

**Comment by lachmanfrantisek** [comment]
Sadly, this is not possible to do. We can get only an encrypted form of the secrets without being able to get the key.
