### ISSUE TITLE
Give reaction on comment commands in GitHub and GitLab

### ISSUE THREAD

**Issue by nikromen** [packit/ogr#630]
According to [packit-service/issues/1081](https://github.com/packit/packit-service/issues/1081) we need to implement `give reaction to the comment` methods for Github and Gitlab.

TODO:
- [ ] give reaction to the Gitlab comment
- [ ] give reaction to the Github comment

**Comment by mfocko** [comment]
I would probably go generic with the reactions (since it is library). GitHub has a limited set of possible reactions, GitLab seems to support any emoji (it is called _Award Emoji_; just in case you'll be looking for it in documentation, cause it's weird name)

**Comment by lachmanfrantisek** [comment]
I agree with @mfocko , we can provide an enum or just a string representation (`:+1:` / `+1`). This will allow more usecases in the future (e.g. :-1: when the user is not allowed to trigger packit, :rocket: when the update has been synced to the distgit e.t.c.)

**Comment by nikromen** [comment]
As we discussed within the team, it would be nice to have this feature also for Pagure but their API doesn't support it. I was doing some research and there was a demand for this feature a year ago, unfortunately without any response. The created issue is [here](https://pagure.io/pagure/issue/5042).
