### ISSUE TITLE
RFE: provide unified interface for git-forge webhook payloads

### ISSUE THREAD

**Issue by TomasTomecek** [packit/ogr#677]
This is an outcome of our 2022 winter hackfest discussion.

The ask is to provide unified classes for webhook payloads of git forges.

We need to research if we should provide object representations of PRs, branches, commits, releases etc. or the actual events: PR created, branch got new commits, release was created etc.

CC @praiskup

**Comment by praiskup** [comment]
From Copr perspective, we need "ChangeRequest" (PR/MR), "Change" (pushed), "ChangeRequestComment" (comment submitted in PR/MR), and somehow releases, but I'm not sure about that one.

**Comment by lachmanfrantisek** [comment]
It might be related to packit/packit-service#1344 and/or PACKIT-202  if we do that in a more general way.
