### ISSUE TITLE
Support instances hosted on subpage like the.hostname/git

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#774]
There are git(lab) instances not hosted on a main hostname, e.g.:

* https://pra.ne.ncsu.edu/gitlab
* https://software.rcc.uchicago.edu/git

Let's make sure everything works well with those instances:
* [ ] URL parsing
* [ ] factory methods (parsing, service matching,...)
* [ ] GitLab API on such instances

**Comment by nforro** [comment]
There have benn no requests for this, closing for now.
