### ISSUE TITLE
Resolving paths

### ISSUE THREAD

**Issue by mfocko** [packit/ogr#838]
### What happened? What is the problem?

GitLab fails to resolve `.` and (potentially) `..` in the paths, this resulted in **not** triggering the TF runs.

Possibly affected methods (as TODO list with confirmed as ticked):
- [x] `GitProject.get_file_content()`
- [ ] `PullRequest.comment()`

### What did you expect to happen?

`ogr` to ignore the `.` and `..` where applicable

### Example URL(s)

Example of sanitization:
https://github.com/packit/packit-service/blob/7337498d73eed935e6196696a518d3ea69ef4ad7/packit_service/worker/helpers/testing_farm.py#L191-L202

This could be probably done in a more generic way in the `packit-service`, that's open for discussion. The linked sanitization is not enough IMO…

### Steps to reproduce

```bash
import os
from ogr import GitlabService

gs = GitlabService(token=os.getenv("GITLAB_TOKEN"))
p = gs.get_project(namespace="efedin", repo="compose-tests")

# generated via f-string in Packit Service
print(p.get_file_content(path="./.fmf/version", ref="84d980d")

# without the `.` prefix
print(p.get_file_content(path=".fmf/version", ref="84d980d")
```

### Workaround

- [X] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [X] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by majamassarini** [comment]
In ogr we want the same behaviour for github, gitlab and pagure. Fix it in packit if this will change the behaviour for gitlab in ogr.

**Comment by lbarcziova** [comment]
`PullRequest.comment()` is not affected as `filename` there is not event considered for GitLab, closing.
